apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: gt2w1xdju-dotnet-basic
  janus-idp.io/tekton: gt2w1xdju-dotnet-basic
  backstage.io/kubernetes-id: gt2w1xdju-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: gt2w1xdju-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
